export const cardList = [
    {
      id:1,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png",
      pokemonId:1
    },
    {
      id:2,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/001.png",
      pokemonId:1
    },
    {
      id:3,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png",
      pokemonId:2
    },
    {
      id:4,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/004.png",
      pokemonId:2
    },
    {
      id:5,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png",
      pokemonId:3
    },
    {
      id:6,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/007.png",
      pokemonId:3
    },
    {
      id:7,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/010.png",
      pokemonId:4
    },
    {
      id:8,
      flipped:false,
      img:"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/010.png",
      pokemonId:4
    }
  ]